### ISSUE TITLE
Middleware for Auth

### ISSUE THREAD

**Issue by Sadmansamee** [damianmarek/express-es6-rest-api-auth#1]
is there any middleware on router to check on every API call if this user logged in or not?

**Comment by damianmarek** [comment]
Yes, use `passport.authenticate('jwt')` as a middleware. If user is not authenticated it will not allow him to access the route and send 401 status code. If he is, it will give you also the req.user to get his data. To pass the authentication the JWT token must be in header named `authorization`.
Example of route
`auth.get('/test', passport.authenticate('jwt') , (req, res) => {
  res.status(200).json({ message: 'Only authenticated user can see this message', auth: req.isAuthenticated(), user: req.user })
})`
